### ISSUE TITLE
如何进行CPython 的性能评价，以及建立可重复的测评自动化过程

### ISSUE THREAD

**Issue by mollybuild** [plctlab/riscv-laptop#4]
研究如何进行 CPython 的性能评价，如何建立可重复的测评自动化过程，后续纳入到PTS中。

**Comment by lazyparser** [comment]
预期在12月17日之前能完成性能基线的评定。

**Comment by mollybuild** [comment]
CPython的官网有对性能的持续监控：
https://speed.python.org/changes/
其中用到了pyperformance作为性能benchmark，使用方法参考：https://pyperformance.readthedocs.io/usage.html

我在x86(Intel Core i7) 和unmatched上分别测试了pyperformance。测试的步骤大概是：
```
$ sudo apt install python3
$ sudo apt install python3-dev
$ sudo apt install python3-pip
$ python3 -m pip install pyperformance
$ pyperformance run --python=/usr/bin/python3 -o py39.json
```
性能测试结果如下：

<html xmlns:v="urn:schemas-microsoft-com:vml"
xmlns:o="urn:schemas-microsoft-com:office:office"
xmlns:x="urn:schemas-microsoft-com:office:excel"
xmlns="http://www.w3.org/TR/REC-html40">

<head>

<meta name=ProgId content=Excel.Sheet>
<meta name=Generator content="Microsoft Excel 15">
<link id=Main-File rel=Main-File
href="file:///C:/Users/MOLLYC~1/AppData/Local/Temp/msohtmlclip1/01/clip.htm">
<link rel=File-List
href="file:///C:/Users/MOLLYC~1/AppData/Local/Temp/msohtmlclip1/01/clip_filelist.xml">
<style>

</style>
</head>

<body link="#0563C1" vlink="#954F72">



Benchmark | Intel Core i7 @1.80GHz + 16G SSD   + python3.8 | Unmatched + 16G SSD + python3.9
-- | -- | --
2to3 | 401 ms +- 5 ms - | 8.81 sec +- 0.08 sec: 22.01x   slower
chaos | 129 ms +- 2 ms - | 3.40 sec +- 0.16 sec: 26.28x   slower
deltablue | 8.14 ms +- 0.23 ms - | 227 ms +- 6 ms: 27.86x slower
fannkuch | 560 ms +- 17 ms - | 10.9 sec +- 0.4 sec: 19.40x slower
float | 133 ms +- 2 ms - | 3.76 sec +- 0.14 sec: 28.34x   slower
go | 295 ms +- 4 ms - | 9.81 sec +- 2.38 sec: 33.29x   slower
hexiom | 11.4 ms +- 0.2 ms - | 306 ms +- 12 ms: 26.80x slower
json_dumps | 15.4 ms +- 0.3 ms - | 382 ms +- 8 ms: 24.88x slower
json_loads | 30.6 us +- 0.6 us - | 577 us +- 12 us: 18.83x slower
logging_format | 12.0 us +- 0.3 us - | 308 us +- 22 us: 25.58x slower
logging_silent | 220 ns +- 31 ns - | 6.00 us +- 0.27 us: 27.29x slower
logging_simple | 11.4 us +- 1.0 us - | 285 us +- 6 us: 25.07x slower
meteor_contest | 126 ms +- 4 ms - | 2.15 sec +- 0.07 sec: 17.03x   slower
nbody | 146 ms +- 3 ms - | 3.12 sec +- 0.13 sec: 21.38x   slower
nqueens | 114 ms +- 2 ms - | 2.70 sec +- 0.10 sec: 23.76x   slower
pathlib | 22.5 ms +- 0.4 ms - | 594 ms +- 13 ms: 26.36x slower
pickle | 11.7 us +- 0.2 us - | 211 us +- 6 us: 18.10x slower
pickle_dict | 28.8 us +- 0.4 us - | 464 us +- 29 us: 16.10x slower
pickle_list | 3.58 us +- 0.06 us - | 66.5 us +- 4.5 us: 18.57x slower
pickle_pure_python | 527 us +- 11 us - | 15.2 ms +- 0.4 ms: 28.80x slower
pidigits | 199 ms +- 3 ms - | 2.40 sec +- 0.01 sec: 12.04x   slower
pyflate | 789 ms +- 9 ms - | 20.9 sec +- 0.4 sec: 26.49x slower
python_startup | 16.9 ms +- 0.3 ms - | 272 ms +- 2 ms: 16.12x slower
python_startup_no_site | 7.00 ms +- 0.10 ms - | 85.1 ms +- 0.3 ms: 12.16x slower
raytrace | 557 ms +- 8 ms - | 15.4 sec +- 0.3 sec: 27.58x slower
regex_compile | 219 ms +- 19 ms - | 4.73 sec +- 0.10 sec: 21.61x   slower
regex_dna | 210 ms +- 7 ms - | 2.73 sec +- 0.04 sec: 12.99x   slower
regex_effbot | 3.58 ms +- 0.21 ms - | 57.7 ms +- 1.9 ms: 16.10x slower
regex_v8 | 26.7 ms +- 1.2 ms - | 460 ms +- 6 ms: 17.25x slower
richards | 78.8 ms +- 4.1 ms - | 2.21 sec +- 0.09 sec: 28.08x   slower
scimark_fft | 404 ms +- 4 ms - | 8.79 sec +- 0.68 sec: 21.78x   slower
scimark_lu | 172 ms +- 4 ms - | 5.04 sec +- 0.19 sec: 29.40x   slower
scimark_monte_carlo | 123 ms +- 7 ms - | 3.09 sec +- 0.26 sec: 25.15x   slower
scimark_sor | 229 ms +- 6 ms - | 6.00 sec +- 0.18 sec: 26.23x   slower
scimark_sparse_mat_mult | 5.41 ms +- 0.09 ms - | 145 ms +- 6 ms: 26.84x slower
spectral_norm | 152 ms +- 2 ms - | 4.11 sec +- 0.34 sec: 27.00x   slower
sqlite_synth | 3.50 us +- 0.13 us - | 87.7 us +- 2.2 us: 25.04x slower
telco | 7.33 ms +- 0.13 ms - | 218 ms +- 12 ms: 29.76x slower
unpack_sequence | 69.7 ns +- 1.7 ns - | 1.35 us +- 0.11 us: 19.37x slower
unpickle | 15.6 us +- 0.3 us - | 316 us +- 4 us: 20.21x slower
unpickle_list | 5.45 us +- 0.12 us - | 102 us +- 5 us: 18.77x slower
unpickle_pure_python | 387 us +- 13 us - | 11.2 ms +- 0.4 ms: 28.83x slower
xml_etree_parse | 185 ms +- 7 ms - | 3.66 sec +- 0.07 sec: 19.81x   slower
xml_etree_iterparse | 122 ms +- 4 ms - | 2.89 sec +- 0.07 sec: 23.65x   slower
xml_etree_generate | 107 ms +- 3 ms - | 2.90 sec +- 0.05 sec: 27.08x   slower
xml_etree_process | 86.6 ms +- 2.9 ms - | 2.43 sec +- 0.06 sec: 28.09x   slower
  |   | Geometric mean:  22.47x   slower



</body>

</html>


其中有9个benchmark在x86和unmatched都Failed了，它们是：
```
9 benchmarks failed:
- chameleon
- crypto_pyaes
- django_template
- dulwich_log
- mako
- sqlalchemy_declarative
- sqlalchemy_imperative
- sympy
- tornado_http
```
