### ISSUE TITLE
移植chromium浏览器

### ISSUE THREAD

**Issue by rebeccasf** [plctlab/riscv-laptop#5]
看了suse，fedora，成功移植了chromium浏览器，我正尝试用chromium推荐的构建方式去编译：
https://chromium.googlesource.com/chromium/src/+/main/docs/linux/build_instructions.md 

我是在ubuntu上面编译，当然在代码上，我有做了一些改动，为了增加对riscv64的支持。
然而无法成功构建，见招拆招。想请问大家有没有共同的问题，大家可以通过这个管道交流经验。
我本人在移植方面没有经验，如果我们可以共享代码，那我们可否合作，把浏览器搞起来？😄

谢谢！

**Comment by lazyparser** [comment]
Hi @rebeccasf 欢迎！所有的代码都是公开哒，不过还有乱。欢迎加入东亚时区RISC-V的技术群撒，可以添加我的微信（fangzhang1024 备注chromium）
